services:
  sb-ex:
    depends_on:
      - sb-ex-postgres
      - sb-ex-pgadmin
    build: .
    ports:
      - 3000:3000
    environment:
      - APP_PORT=3000
      - DB_HOST=sb-ex-postgres
      - DB_USER=postgres
      - DB_PASS=pass
      - DB_PORT=5432
      - CACHE_TTL=60000 # 1 minute
  sb-ex-postgres:
    image: postgres:18.3
    environment:
      - POSTGRES_PASSWORD=pass
  sb-ex-pgadmin:
    depends_on:
      - sb-ex-postgres
    image: dpage/pgadmin4:9.13.0
    user: root
    ports:
      - 3100:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGPASS_FILE=/tmp/pgpass/.pgpass
    volumes:
      - type: bind
        source: ./pgAdmin/servers.json
        target: /pgadmin4/servers.json
      - type: bind
        source: ./pgAdmin/.pgpass
        target: /tmp/pgpass/.pgpass
    entrypoint: >
      /bin/sh -c "
      sudo chown 5050:5050 /tmp/pgpass/.pgpass;
      chmod 600 /tmp/pgpass/.pgpass;
      /entrypoint.sh
      "
